### ISSUE TITLE
What's x1,x2 and y

### ISSUE THREAD

**Issue by kingkins** [IsaacPatole/SwapNet#1]
Dear Isaac
x1 = human A
x2 = human B
y = ?

Could you hint me?
Thanks~

**Comment by init-22** [comment]
Hey @kingkins so sorry for the delayed response ! I think you might have got the answer by now.
SwapNet is mostly used for garment transfer, let me give you an example to explain this:
x1 = person A wearing white shirt
x2 = person B wearing blue shirt
y = person A wearing person B's shirt. this way we train the model and it learns to swap cloths.

connect with me on LinkdIn if you any more questions on this.


Thanks, 
Isaac
